### ISSUE TITLE
Please consider supporting bpfilter packet filtering

### ISSUE THREAD

**Issue by joshtriplett** [alessandrod/aya#16]
bpfilter is a packet-filtering mechanism similar to iptables and nftables; see https://lwn.net/Articles/747551/ for details. I'd love to have support for bpfilter in aya.

**Comment by alessandrod** [comment]
I just had a look and it seems that as of today bpfilter doesn't do much yet. Only the basic infrastructure was merged, but the actual code to translate the netfilter API to XDP rules was never merged. See https://lwn.net/Articles/822744/, https://lwn.net/ml/linux-fsdevel/875zc4c86z.fsf_-_@x220.int.ebiederm.org/ and the last effort to revive it https://lore.kernel.org/bpf/20210517225308.720677-1-me@ubique.spb.ru.

**Comment by joshtriplett** [comment]
Looks like you're right. Thanks for looking into it; sounds like that isn't a good path forward.
