### ISSUE TITLE
the pid argument of kprobe.attach doesn't work

### ISSUE THREAD

**Issue by evilsocket** [alessandrod/aya#19]
According [to the documentation](https://docs.rs/aya/0.10.2/aya/programs/struct.KProbe.html#method.attach):

> If pid is not None, the program executes only when the target function is triggered by the given pid.

This however doesn't seem to be the case, the kprobe is executed in the context of the calling pid, not the target pid.

For instance, i'm using this probe, trying to block syscalls selectively:

```c
#include <uapi/linux/bpf.h>
#include <bpf_helpers.h>
#include <bpf_map.h>

#define EPERM 1

SEC("kprobe/on_blocked_syscall")
int on_blocked_syscall(void *ctx)
{
	bpf_override_return(ctx, -EPERM);
	return 0;
}

char _license[] SEC("license") = "GPL";

unsigned int _version SEC("version") = 0xFFFFFFFE;
```

I've compiled this probe with clang and hardcoded the object file as a Vec<u8>, that I'm now using like this:

```rust
use std::convert::TryInto;
use std::fs;

use aya::{programs::KProbe, Bpf, Btf};

mod probe;

fn main() {
    // target pid
    let target = 4545;
    // load the program
    let data = probe::DATA.to_vec(); // probe::DATA is just a lazy_static Vec<u8>
    let mut bpf = Bpf::load(&data, Btf::from_sys_fs().ok()).unwrap();
    // load the generic kprobe
    let kprobe = bpf.program_mut("on_blocked_syscall").unwrap();
    let kprobe: &mut KProbe = kprobe.try_into().unwrap();

    kprobe.load().unwrap();

    kprobe.attach("__x64_sys_openat", 0, Some(target)).unwrap();

    println!("kprobe attached, now trying to open a file ...");

    fs::read_to_string("/path/to/some/readable/file.txt").unwrap();

    // some blocking operation here
}
```

Since I'm targeting process 4545 with the attach invocation, I expect the `fs::read_to_string` call to work, while it instead fails with:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', src/main.rs:29:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

And while the program is running, this also seems to apply to all the other processes, for instance:

```
[  393.127994] systemd-journald[298]: Failed to open runtime journal: Operation not permitted
[  393.128037] systemd-journald[298]: Failed to open runtime journal: Operation not permitted
[  393.128069] systemd-journald[298]: Failed to open runtime journal: Operation not permitted
[  393.128109] systemd-journald[298]: Failed to open runtime journal: Operation not permitted
[  393.128143] systemd-journald[298]: Failed to open runtime journal: Operation not permitted
[  393.128178] systemd-journald[298]: Failed to open runtime journal: Operation not permitted
[  393.128217] systemd-journald[298]: Failed to open runtime journal: Operation not permitted
[  393.128260] systemd-journald[298]: Failed to open runtime journal: Operation not permitted
[  393.128300] systemd-journald[298]: Failed to open runtime journal: Operation not permitted
[  393.128335] systemd-journald[298]: Failed to open runtime journal: Operation not permitted
[  399.016623] systemd-journald[298]: Failed to open runtime journal: Operation not permitted
[  758.871870] systemd-journald[298]: Failed to open runtime journal: Operation not permitted
```

Using aya from master:

`aya = { git = "https://github.com/alessandrod/aya", branch = "main" }
`

**Comment by alessandrod** [comment]
Unfortunately it looks like only uprobes can be attached to a single task, and if you think about how kprobes are implemented, it kinda makes sense. I have removed the pid argument from `KProbe::attach`. 

To do what you have in mind, you'll have to do something like:

```rust
    let mut bpf = Bpf::load(&code, None)?;

    let mut target_pids = HashMap::try_from(bpf.map_mut("TARGET_PIDS")?)?;
    target_pids.insert(1234i32, 1i32, 0)?;

    let prog: &mut KProbe = bpf.program_mut("block_openat")?.try_into()?;
    prog.load()?;
    prog.attach("__x64_sys_openat", 0)?;
```

and then bpf side:

```rust
#![no_std]
#![no_main]

use aya_bpf::{
    helpers::bpf_override_return,
    macros::{kprobe, map},
    maps::HashMap,
    programs::ProbeContext,
    BpfContext,
};

#[map]
static mut TARGET_PIDS: HashMap<i32, i32> = HashMap::with_max_entries(1024, 0);

#[panic_handler]
fn do_panic(_info: &core::panic::PanicInfo) -> ! {
    unreachable!()
}

const EPERM: i64 = 1;

#[kprobe]
fn block_openat(ctx: ProbeContext) {
    let pid = ctx.pid() as i32;
    unsafe {
        if TARGET_PIDS.get(&pid).is_some() {
            bpf_override_return(ctx.as_ptr() as *mut _, -EPERM as u64);
        }
    }
}
```

**Comment by evilsocket** [comment]
yeah i thought it was a bit weird, but i was hopeful :D thanks for your answer ... since we're here, could you point me to any doc explaining how to compile a rust based ebpf probe like in this example? thanks a lot Ale!

**Comment by evilsocket** [comment]
PS: is there a way I can donate to you and/or this project?

**Comment by alessandrod** [comment]
> yeah i thought it was a bit weird, but i was hopeful :D thanks for your answer ... since we're here, could you point me to any doc explaining how to compile a rust based ebpf probe like in this example? thanks a lot Ale!

You need a recent nightly (from the last couple of weeks), then it's as easy as:

```
cargo +nightly build --target=bpfel-unknown-none -Z build-std=core 
```

**Comment by alessandrod** [comment]
> PS: is there a way I can donate some bucks to you and/or this project?

Not yet, planning to look at options soon!

**Comment by evilsocket** [comment]
oh man that's going to make my life so much easier, thanks again :D

**Comment by alessandrod** [comment]
> > yeah i thought it was a bit weird, but i was hopeful :D thanks for your answer ... since we're here, could you point me to any doc explaining how to compile a rust based ebpf probe like in this example? thanks a lot Ale!
> 
> You need a recent nightly (from the last couple of weeks), then it's as easy as:
> 
> ```
> cargo +nightly build --target=bpfel-unknown-none -Z build-std=core 
> ```

Forgot to mention you need to install this before you can cargo build https://github.com/alessandrod/bpf-linker

So much doc to write! 😂

**Comment by evilsocket** [comment]
as you've probably figured already i'm not very expert with rust, but let me know if there's something i can do to help :D meanwhile i'll keep using the library and reporting bugs 👍🏻
