### ISSUE TITLE
Invalid ELF header size or alignment

### ISSUE THREAD

**Issue by tw4452852** [alessandrod/aya#24]
A weird issue occurred today that puzzled me a lot. When I used `load_file(xxx)`, everything worked fine. But if I used `load(include_bytes!(xxx), None)`, it produced this error:

```
Error: error parsing BPF object

Caused by:
    0: error parsing ELF data
    1: Invalid ELF header size or alignment
```

Anyone knows why? Thanks in advance.

**Comment by ecarrara** [comment]
@tw4452852 i think you should align you array of bytes.

> Zero-copy buffer mode
>      bpf devices may also operate in the BPF_BUFMODE_ZEROCOPY mode, in which
>      packet data is written directly into two user memory buffers by the ker-
>      nel, avoiding both	system call and	copying	overhead.  Buffers are of
>      fixed (and	equal) size, page-aligned, and an even multiple	of the page
>      size.  The	maximum	zero-copy buffer size is returned by the BIOCGETZMAX
>      ioctl.  Note that an individual packet larger than	the buffer size	is
>      necessarily truncated.
>  https://www.freebsd.org/cgi/man.cgi?bpf(4)

What works for me:

```rust
macro_rules! include_bytes_align_as {
    ($align_ty:ty, $path:literal) => {{
        #[repr(C)]
        pub struct AlignedAs<Align, Bytes: ?Sized> {
            pub _align: [Align; 0],
            pub bytes: Bytes,
        }

        static ALIGNED: &AlignedAs<$align_ty, [u8]> = &AlignedAs {
            _align: [],
            bytes: *include_bytes!($path),
        };

        &ALIGNED.bytes
    }};
}

static PROGRAM_DATA: &'static [u8] = include_bytes_align_as!(
    u32,
    "../../target/bpfel-unknown-none/release/libpq-tracer-bpf"
);

    // ..
    let mut bpf = Bpf::load(PROGRAM_DATA.into(), None)?;
```

I copied the `include_bytes_align_as` macro [from here]( https://jack.wrenn.fyi/blog/include-transmute/).

**Comment by tw4452852** [comment]
Wow, thanks @ecarrara , Now it's clear now.
