### ISSUE TITLE
allow multiple BPF programs to share the same BTF

### ISSUE THREAD

**Issue by evilsocket** [alessandrod/aya#30]
I've noticed that multiple BPF programs loaded by the same userspace process can't share the same host BTF because [this method](https://github.com/alessandrod/aya/blob/d996a88de47d60053504695036a14157ce6b3aa6/aya/src/bpf.rs#L114) consumes the `target_btf` object instead of accepting it by reference. However, [later in the code](https://github.com/alessandrod/aya/blob/d996a88de47d60053504695036a14157ce6b3aa6/aya/src/obj/btf/relocation.rs#L181), in the only part where `target_btf` is used (immutably), its reference is used. If i'm not mistaken this means that the very first method could accept a reference instead of a value to begin with.

On my Ubuntu each BTF object is around 13MB (in debug mode) and I'm loading several different eBPF programs, so it'd be nice to be able to share the relocation info among them and save a lot of memory.

**Comment by alessandrod** [comment]
Yup, makes sense.

**Comment by evilsocket** [comment]
since (at least in my case) it'd be a BTF instance shared among different threads, should it be an Arc<Mutex<Btf>> ?

**Comment by evilsocket** [comment]
mmm nevermind this was a dumb question, the logic to access it should not be coupled with the library, so i'd say Btf::load should just accept an `Option<&Btf>` and then one can handle the more appropriate borrowing strategy from the outside (in my case it'd be `Arc<Mutex<&Btf>>`) ... thoughts?

**Comment by alessandrod** [comment]
Yep that sounds right!

**Comment by evilsocket** [comment]
great, working on a PR

**Comment by evilsocket** [comment]
I can confirm this reduces the memory usage significantly in a multiple eBPF programs scenario, now I'm simply:

```rust
lazy_static! {
  static ref HOST_BTF: Option<Btf> = {
    let start = Instant::now();
    let maybe_btf = Btf::from_sys_fs().ok();
    let duration = start.elapsed();
    if maybe_btf.is_none() {
      warn!("no host BTF information found");
    } else {
      debug!("host btf loaded in {:?}", duration);
    }
    maybe_btf
  };
}
```
and then sharing it with all programs via `HOST_BTF.as_ref()` ... even better that `Arc<Mutex<Btf>>` because it does not require locking. 

Maybe aya itself could load this Btf singlenton (enabled by default, opt-out with configuration?) and expose it?

**Comment by alessandrod** [comment]
I imagine that most programs won't need to store the BTF info. They'll load it, call `Bpf::load` from the main thread and then deallocate it. What's your use case? Why do you need to store it and why are you calling `load` from multiple threads?

**Comment by evilsocket** [comment]
I'm building something very modular, where each module has a user land component and an eBPF component. Due to their different functional nature I'm compiling and loading those eBPF programs individually, each module lives in its own (userland) thread and loads the eBPF program(s) it needs. For this reason I needed to centralize the BTF info so they could all be relocated with the same object.
