### ISSUE TITLE
can't load programs: btf relocations consume all available memory

### ISSUE THREAD

**Issue by dave-tucker** [alessandrod/aya#34]
Tyring to load a simple `XDP` program that was built with Aya:

```
./examples/target/bpfel-unknown-none/debug/xdp: file format elf64-bpf


Disassembly of section xdp/xdp_stats:

0000000000000000 <xdp_stats>:
       0:       b7 00 00 00 02 00 00 00 r0 = 2
       1:       95 00 00 00 00 00 00 00 exit
```

I've verified that this program can be loaded with `sudo bpftool prog load ./examples/target/bpfel-unknown-none/debug/xdp /sys/fs/bpf/xdp_stats`

However, loading this from Aya is not possible due to something weird with the BTF relocations.

The snippet of my main.rs that loads the code looks like this:
```rust
let mut bpf = Bpf::load_file(path)?;
```

When run, the program gets stopped by the oom-killer.
Running with strace reveals the following, after reading from `/sys/kernel/btf/vmlinux`

```
mmap(NULL, 1863680, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa0e61aa000
brk(0x5619e237b000)                     = 0x5619e237b000
brk(0x5619e239c000)                     = 0x5619e239c000
mmap(NULL, 331776, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa0e6159000
mremap(0x7fa0e6159000, 331776, 659456, MREMAP_MAYMOVE) = 0x7fa0e60b8000
mremap(0x7fa0e60b8000, 659456, 1314816, MREMAP_MAYMOVE) = 0x7fa0e5f77000
mremap(0x7fa0e5f77000, 1314816, 2625536, MREMAP_MAYMOVE) = 0x7fa0e5cf6000
mremap(0x7fa0e5cf6000, 2625536, 5246976, MREMAP_MAYMOVE) = 0x7fa0e57f5000
mremap(0x7fa0e57f5000, 5246976, 10489856, MREMAP_MAYMOVE) = 0x7fa0e4df4000
mremap(0x7fa0e4df4000, 10489856, 20975616, MREMAP_MAYMOVE) = 0x7fa0e39f3000
mremap(0x7fa0e39f3000, 20975616, 41947136, MREMAP_MAYMOVE) = 0x7fa0e11f2000
mremap(0x7fa0e11f2000, 41947136, 83890176, MREMAP_MAYMOVE) = 0x7fa0dc1f1000
mremap(0x7fa0dc1f1000, 83890176, 167776256, MREMAP_MAYMOVE) = 0x7fa0d21f0000
mremap(0x7fa0d21f0000, 167776256, 335548416, MREMAP_MAYMOVE) = 0x7fa0be1ef000
mremap(0x7fa0be1ef000, 335548416, 671092736, MREMAP_MAYMOVE) = 0x7fa0961ee000
mremap(0x7fa0961ee000, 671092736, 1342181376, MREMAP_MAYMOVE) = 0x7fa0461ed000
mremap(0x7fa0461ed000, 1342181376, 2684358656, MREMAP_MAYMOVE) = 0x7f9fa61ec000
mremap(0x7f9fa61ec000, 2684358656, 5368713216, MREMAP_MAYMOVE) = 0x7f9e661eb000
mremap(0x7f9e661eb000, 5368713216, 10737422336, MREMAP_MAYMOVE) = 0x7f9be61ea000
^C--- SIGINT {si_signo=SIGINT, si_code=SI_KERNEL} ---
```

This issue can be worked around by using the following to load the code:

```rust
 let data = fs::read(path)?;
 let mut bpf = Bpf::load(&data,None)?;
```

Running on Fedora 34, Kernel 5.13.4.

**Comment by alessandrod** [comment]
I can't seem to be able to reproduce this with a custom built 5.8 kernel. Could you please run the program in a debugger, let it run for a while, then interrupt and get a stack trace?

**Comment by dave-tucker** [comment]
@alessandrod 
this loop appears to be the problem...
![image](https://user-images.githubusercontent.com/3781777/127317495-bd2fd810-c2bd-4d74-93f0-2473639ccc96.png)

The Vec continues to grow unbounded :scream:

**Comment by dave-tucker** [comment]
@alessandrod ok I've got a root cause for you...
bindings for `BTF_KIND_FLOAT` are missing.
when the code encouters a float it reads it as `UNKNOWN` and then continues to re-read the same data over and over.
