### ISSUE TITLE
Add bpf_trace_printk helper

### ISSUE THREAD

**Issue by dave-tucker** [alessandrod/aya#39]
Getting information from BPF programs at runtime is hard and `bpf_trace_printk` is a helpful tool for development (but definitely not production).

**Comment by dave-tucker** [comment]
I'm going to go ahead an close this. From discord:

```
alessandrod — 03/08/2021: I never bothered to wrap bpf_trace_printk since it's a variadic function, and while rust supports FFI with those, it's super clunky
so what I usually do is define my per-crate logging library that uses a PerfEventArray, kinda like what we're planning to do
```

So #40 looks to be the best path forward.

**Comment by evilsocket** [comment]
@dave-tucker are you certain that PerfEventArray can be used in any context where bpf_trace_printk might be required? I remember trying it recently in XDP and receiving a -2 error on submit ... i admit i'm new to eBPF so that might just me being noob, but I have a number of other programs (non XDP) working great using the same PerfEventArray code

**Comment by dave-tucker** [comment]
@evilsocket no I'm not certain :wink: i don't see any reason why it shouldn't work, but then again nothing would surprise me.
i'll give it a try in the next few days and let you know!

**Comment by evilsocket** [comment]
yes i assumed it would have worked too, alas :D thanks for looking into it

**Comment by dave-tucker** [comment]
@evilsocket here you go: https://gist.github.com/dave-tucker/8c8967888c8d315c98acd4499ed41abc
that works for me on kernel 5.13.4. could be a kernel version issue :thinking:

**Comment by evilsocket** [comment]
I'm using [this code](https://gist.github.com/evilsocket/7f31b20d4595939f7812bb926e913226#file-xdp_perf-c-L133) and keep getting a -2 on that line, on 5.11.0-25 ... if you can help me compile your code I can try it locally to see if it behaves differently than on 5.13.4

**Comment by evilsocket** [comment]
that is my very first XDP attempt, so far i've been mostly playing with kprobes and tracepoints, apologies for the hacks :D

**Comment by evilsocket** [comment]
@dave-tucker i've used your `aya-template` to build that code and it works on my system, clearly there's an issue with my C code ... all good, thanks 👍🏻

**Comment by evilsocket** [comment]
it turns out i'm dumb and bpf_perf_event_output returns -2 if there's no userspace component reading the ring buffer :D
