### ISSUE TITLE
how to properly compile ebpf programs for aya?

### ISSUE THREAD

**Issue by evilsocket** [alessandrod/aya#6]
Hi, first of all thanks so much for this library, it was so needed.

I've been trying to use it to load a eBPF program which relies on tracepoints. The program has been compiled using clang with:

```
clang \
	-D__KERNEL__ \
	-D__BPF_TRACING__ \
	-D__TARGET_ARCH_$(linux_arch) \
	-O2 -target bpf \
	-Wno-address-of-packed-member \
	-Wno-compare-distinct-pointer-types \
	-Wno-deprecated-declarations \
	-Wno-gnu-variable-sized-type-not-at-end \
	-Wno-pointer-sign \
	-Wno-pragma-once-outside-header \
	-Wno-unknown-warning-option \
	-Wno-unused-value \
	-Wunused \
	-Wall \
	-fno-stack-protector \
	-fno-jump-tables \
	-fno-unwind-tables \
	-fno-asynchronous-unwind-tables \
	-xc \
	-I . \
	-I /usr/include/${ARCH}-linux-gnu/ \
	-I ${LINUX_HEADERS_ROOT}/include \
	-I ${LINUX_HEADERS_ROOT}/include/uapi \
	-I ${LINUX_HEADERS_ROOT}/include/generated \
	-I ${LINUX_HEADERS_ROOT}/include/generated/uapi \
	-I ${LINUX_HEADERS_ROOT}/tools/testing/selftests \
	-I ${LINUX_HEADERS_ROOT}/arch/${linux_arch}/include \
	-I ${LINUX_HEADERS_ROOT}/arch/${linux_arch}/include/generated \
	-I ${LINUX_HEADERS_ROOT}/arch/${linux_arch}/include/generated/uapi \
	-c $< -o $@
```

While the object file works perfectly with other libraries (goebpf), I was unable to load it with Aya, specifically it fails to find any programs with the specified name (or any programs at all, I tried to enumerate the programs attribute and it's empty).

So I assume there's a specific way to compile the object OR to name functions according to what Aya expects? I'd appreciate if you guys could shed some light on this.

Thanks.

**Comment by seanyoung** [comment]
It would be helpful to know what files you are compiling so we can reproduce the issue.

The section name should be prefixed with the program type, e.g. `lirc_mode2/`.

**Comment by alessandrod** [comment]
I just pushed a fix I think. There was a typo, we were parsing "trace_point/" as the section prefix but it should be "tracepoint/".

@evilsocket can you try depending on:
```
aya = { git = "https://github.com/alessandrod/aya", branch = "main" }
```

and see if that fixes it?

**Comment by evilsocket** [comment]
@alessandrod sure i can try in a few ... i couldn't find in the documentation what naming convention Aya expects for the programs tho, that'd be a very important piece to add I believe :D

**Comment by alessandrod** [comment]
Same as libbpf and gobpf, barring typos 😅

**Comment by alessandrod** [comment]
I did some refactoring around parsing section names this morning and verified that tracepoints do work now.

**Comment by evilsocket** [comment]
can confirm it works! i am now able to load the object file, load and attach a tracepoint and use a PerfEventArray, thanks for the fixes!

I still have troubles using two tracepoints, but that's not related to the object format itself, will open another issue or ask on discord.
